version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-achat
    restart: always
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - achat-network

volumes:
  mysql_data:

networks:
  achat-network:
    driver: bridge
